### ISSUE TITLE
need more customization

### ISSUE THREAD

**Issue by softmarshmallow** [furkantektas/timeline_list#11]
![File](https://user-images.githubusercontent.com/16307013/80676612-1a871300-8af2-11ea-87a4-0791355e7c0b.jpg)

here is example of shopify's time line. this library needs to be more flexible to support developers to use with advance as such.

**Comment by JHBitencourt** [comment]
You can achieve this design with [timeline_tile](https://github.com/JHBitencourt/timeline_tile).

Also, the [beautiful_timelines](https://github.com/JHBitencourt/beautiful_timelines) repository contains some examples built with this package.

**Comment by furkantektas** [comment]
Thanks for the request. v0.1.0 brings a lot of customisation, please check out the examples.
