### ISSUE TITLE
Is it possible to use IconButton instead of Icon in the timeline?

### ISSUE THREAD

**Issue by shunnokw** [furkantektas/timeline_list#12]
Is it possible to use IconButton instead of Icon in the timeline?
Or is there any onpressed callback on the icon?
Thank you

**Comment by JHBitencourt** [comment]
@shunnokw  you can implement this with the package [timeline_tile](https://github.com/JHBitencourt/timeline_tile). 
It allows to provide your custom indicator to the tiles.

**Comment by furkantektas** [comment]
Thank you for the request, it is now the default behaviour as of v0.1.0. Please check out the examples.
