### ISSUE TITLE
Icon position configurable.

### ISSUE THREAD

**Issue by HarshaiOS1** [furkantektas/timeline_list#14]
Right now the content is configurable(random, left, right and center) but the milestone icon stays in the middle(refer image). please provide option to configure positition of icons
<img width="116" alt="Screenshot 2021-01-20 at 2 09 27 PM" src="https://user-images.githubusercontent.com/46565732/105149295-6454d500-5b29-11eb-9d38-a2567498c678.png">

**Comment by furkantektas** [comment]
It's now supported on v0.1.0 using `MarkerIconAlignment` property. Please check out the examples. Thanks for reporting.
