### ISSUE TITLE
Why based of ListView?

### ISSUE THREAD

**Issue by JonasJW** [furkantektas/timeline_list#2]
I like the package but I would prefer it if it wasn't implemented with a ListView. 

If it was based on a Column I could wrap it in my own ListView. This way I can have other Widgets, that should not be included in my timeline within a scrolling List.

**Comment by furkantektas** [comment]
Because it was easier :) 
In the latest version (0.0.4), @JJCLane added support for custom scroll physics which can solve this issue.

**Comment by shahminrazali** [comment]
HI, where can I find info for custom scroll physics.

Trying to implement it in my own list view as well.
