### ISSUE TITLE
Widget instead of Icon?

### ISSUE THREAD

**Issue by dkobia** [furkantektas/timeline_list#3]
I'd love to be able to use an image instead of an icon. **ImageIcon** alone would suffice.

**Comment by furkantektas** [comment]
Definitely, it'd be great. `ImageIcon` may work for most of the cases but a widget under a`ConstrainedBox` may fit better for general usage. What do you think?

I may not implement such a feature in near future, you can send a PR if it's urgent for your case.

**Comment by martinsedoo1** [comment]
Hi, it'd be great to have **ImageIcon** instead of Icon.

**Comment by Mohanedy98** [comment]
is there any way yet to use text widget instead of icon ?

**Comment by furkantektas** [comment]
@Mohanedy98 currently not possible. You may modify the plugin, it would work since Icon is basically a TextView.

**Comment by Mohanedy98** [comment]
> @Mohanedy98 currently not possible. You may modify the plugin, it would work since Icon is basically a TextView.

What should I change to be able to use text instead as I am still beginner in flutter and it's urgent for me to use it like that

**Comment by furkantektas** [comment]
@Mohanedy98 you can change the Icon widget [here](https://github.com/furkantektas/timeline_list/blob/master/lib/src/timeline_item.dart#L28) to Text Widget.

**Comment by cgestes** [comment]
Did anyone implemented it?

**Comment by furkantektas** [comment]
It is implemented in v0.1.0. Thanks for the feedback!
