### ISSUE TITLE
Place circle marker on the top of the content

### ISSUE THREAD

**Issue by willesmar** [furkantektas/timeline_list#4]
There is an way to place circle marker on the top of the content?

**Comment by furkantektas** [comment]
Current version does not have that option but it is nice-to-have for future.

**Comment by eastrd** [comment]
A bit late, but you can instead use a Container with padding at the top to move the circle marker above the content.

**Comment by JHBitencourt** [comment]
You could do this with [timeline_tile](https://github.com/JHBitencourt/timeline_tile).

Also, the [beautiful_timelines](https://github.com/JHBitencourt/beautiful_timelines) repository contains some examples built with this package.
