### ISSUE TITLE
How to scroll to the item when push back?

### ISSUE THREAD

**Issue by ericgarner** [furkantektas/timeline_list#8]
Hi Team,

I would like to scroll the screen to the Timeline item when click to back button. How could I do that? 
Thanks.

**Comment by furkantektas** [comment]
Hi Eric,
Timeline List uses a ListView underneath. You may use [ScrollController](https://api.flutter.dev/flutter/widgets/ScrollController-class.html) and/or [PageStorageKey](https://api.flutter.dev/flutter/widgets/PageStorageKey-class.html) to preserve scroll location.

**Comment by ericgarner** [comment]
Thanks furkantektas, it worked.

**Comment by furkantektas** [comment]
You are welcome!
